In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("../files_raw/GenZ_DatingApp_Data.csv")

In [5]:
df.head()

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality

In [6]:
# Last column modifying
df[['Priority_1', 'Priority_2', 'Priority_3']] = df['Partner_Priorities'].str.split(' > ', expand=True)

In [7]:
df.drop(columns=['Partner_Priorities'], inplace=True)

In [7]:
df.head()

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Priority_1,Priority_2,Priority_3
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values,Personality,Appearance
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values,Personality,Appearance
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values,Personality,Appearance
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality,Interests,Values
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance,Interests,Personality

In [12]:
df.to_csv("GenZ_DatingApp_Cleaned.csv", index=False)

In [8]:
# Function to convert "Daily Usage Time" to numeric (in hours)
def convert_usage_time(time_str):
    if pd.isna(time_str):
        return None  # Handle missing values
    elif "hour" in time_str:
        return float(time_str.split()[0])  # Extract the number before "hour"
    elif "minutes" in time_str or "minute" in time_str:
        return float(time_str.split()[0]) / 60  # Convert minutes to hours
    else:
        return None  # Handle unexpected cases

In [9]:
df["Daily_Usage_Hours"] = df["Daily_Usage_Time"].apply(convert_usage_time)

In [10]:
df.drop(columns=["Daily_Usage_Time"], inplace=True)

In [11]:
df.head()

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Priority_1,Priority_2,Priority_3,Daily_Usage_Hours
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values,Personality,Appearance,1.0
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,Casual Dating,5,Time-Wasting,Video Calls,Text,Values,Personality,Appearance,0.5
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values,Personality,Appearance,2.0
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality,Interests,Values,0.5
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance,Interests,Personality,2.0